### ISSUE TITLE
Add a clear command.

### ISSUE THREAD

**Issue by moonstar-x** [greencoast-studios/discord-gcs-variety#9]
This command should have an int argument and remove the argument number of messages above. It will need manage messages permissions.

**Comment by tanb01** [comment]
Done ef912aa760ce68642409af10b7f47622487ba2d5

**Comment by moonstar-x** [comment]
Right now the current message reply when you delete the messages is `@user, has deleted ${messages}.`, it should end with "messages" as well. Additionally, since this command is technically to remove messages, leaving a message reply (about the message deletion) doesn't make much sense. Instead, I think this message should show up for some time and after a certain timeout, say 5 seconds, it also gets deleted. For this reason I'm reopening this issue.

**Comment by moonstar-x** [comment]
Done in (6fa1df76e1edbb9a6b622dfe4e702a6cf659b139).

**Comment by moonstar-x** [comment]
> Done in ([6fa1df7](https://github.com/greencoast-studios/discord-gcs-variety/commit/6fa1df76e1edbb9a6b622dfe4e702a6cf659b139)).

Issuing the command `$prefix clear 1` would delete only the issuing command and not the message that was intended to be deleted.

Fixed in (472b6ec2b46c21fbed728b6e771e4bc0fa5b14a9).
